apiVersion: v1
kind: Service
metadata:
  name: hello-kubernetes-loadbalancer
spec:
  selector:
    app: hello-kubernetes
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 5000
  type: LoadBalancer